### ISSUE TITLE
Support for pre 1.7 not correct

### ISSUE THREAD

**Issue by palm86** [BertrandBordage/django-cachalot#10]
I get the following after applying a migration in 1.6:

db_alias = kwargs['using'] if django_version >= (1, 7) else kwargs['db']
KeyError: u'db'

**Comment by BertrandBordage** [comment]
Are you using South <= 0.8.2?

**Comment by palm86** [comment]
I'm afraid I was. Sorry. Works with latest South, thanks. :)
