### ISSUE TITLE
Add linked tables

### ISSUE THREAD

**Issue by paddymul** [BertrandBordage/django-cachalot#101]
I have some django models that are backed by views.  Can you add something so that when the cache for table A is invalidated, table B's cache is also invalidated.  This could be specified in the Meta: section of the model.  Nice work on the module, it has been a really easy drop in speed up.

**Comment by BertrandBordage** [comment]
What’s the purpose of adding such a feature? If you change table A, any query implying table A will be invalidated, even if it’s through relations. In other words, you don’t have to bother about invalidation, it works perfectly without help.

If you really want to add some behaviour at the moment a table is invalidated, use [the `post_invalidation` signal](http://django-cachalot.readthedocs.io/en/latest/quickstart.html#signal).

Apart from that, we can’t add attributes to the `Meta` class of a model, there is a whitelist in Django so we can’t add anything to this class.

And glad you enjoy using this module :)
