### ISSUE TITLE
Adding 'cachalot' to INSTALLED_APPS makes test suite four times slower

### ISSUE THREAD

**Issue by ramiro** [BertrandBordage/django-cachalot#11]
We are evaluating django-cachalot. We are using:
- django-cachalot 1.0.0
- Django 1.6.8
- Postgres 9.3 and 9.4

Other possibly relevant package we use is django-transaction-hooks 0.2.

We noticed that when we have `'cachalot'` present in `INSTALLED_APPS` our test suite run time goes to 600+ seconds. Commenting it out makes that go back to 160+ seconds.

(Found this trying to debug some lockups we are seeing in our CI environment when:
* Running the full South migration history
* Running our test suite

which made us to go back and run the test suite in our local development environment.)

Caching backend is memcached. Memory assigned to it with  `-m` doesn't seem to have any influence in observed behavior.

I'll try to isolate the test cases which actually are the ones that get slower, in the meanwhile I wanted to open this issue because the slowdown happens even when the `CACHALOT_ENABLED` setting is False.

**Comment by JockeTF** [comment]
I'm seeing a slight (and expected) slowdown with the following configuration:

* Cachalot 1.0.0
* Django 1.7.7
* PosgtreSQL 9.4

It is nowhere nears as drastic as yours, but our test data is initialized at module level.

With Cachalot enabled using PyLibMC and CACHALOT_ENABLED=False: `31.079s`
Without Cachalot: `29.665s`

**Comment by ramiro** [comment]
Further finding: The tests from our suite which suffered from the slowdown were, unsurprisingly, the `TransactiontestCase` ones.

So I went trying to make more monkey patching code obey CACHALOT_ENABLED

The most effective change was making the post syncdb/[South] migrations signal receiver to  return early in that case:
```
diff --git a/cachalot/monkey_patch.py b/cachalot/monkey_patch.py
index 1013617..ba67caf 100644
--- a/cachalot/monkey_patch.py
+++ b/cachalot/monkey_patch.py
@@ -178,6 +178,8 @@ def _patch_tests():
 
 
 def _invalidate_on_migration(sender, **kwargs):
+    if not cachalot_settings.CACHALOT_ENABLED:
+        return
     db_alias = kwargs['using'] if django_version >= (1, 7) else kwargs['db']
     invalidate_all(db_alias=db_alias)
 
```
Making the `inner()` functions of `_patch_cursor()`, `_patch_tests()` also help somewhat to get tets run times back to its original values. Haven't tried touchong `_patch_write_compiler()` `_patch_atomic()` yet. 

Not totally sure this is totally correct is given the ability of Cachalot setting to be changed at runtime.

**Comment by BertrandBordage** [comment]
@ramiro & @JockeTF: I also have exactly the same setups as you: PostgreSQL 9.4 in dev, 9.3 in prod, Django 1.6 & 1.7 (depending on the project) and cachalot 1.0.0. [One of these projects](https://github.com/dezede/dezede/blob/master/dezede/settings/base.py#L40) also uses django-transaction-hooks.  The only difference is that I use Redis and stopped using memcached almost 2 years ago.

I also measured a small slowdown: 79 s with cachalot & 75 s without.

@ramiro:

I don’t have a solution yet: invalidating the cache, whether `CACHALOT_ENABLED` is `True` or not is the best solution I found to avoid invalidation issues after disabling/enabling it. So the solution to skip invalidation on migrations if `CACHALOT_ENABLED` is bad in my opinion.

By the way, it’s strange that `_invalidate_on_migration` has such an effect on your tests. Do you have hundreds of migrations?  Besides, I think `_patch_tests` has a much significant effect on tests, as it invalidates the cache before each `test_[something]` method.

Could you test again with and without cachalot using `SOUTH_TESTS_MIGRATE = False`, please? It’s to make sure the huge slowdown is really coming from `_invalidate_on_migration`.

**Comment by BertrandBordage** [comment]
@ramiro: Could you test again using django-cachalot 1.0.2, please? I greatly improved the automatic invalidation speed, so it could have a significant impact on this issue.

**Comment by ramiro** [comment]
@BertrandBordage Sure, will do that in the next fewa days and report back here. Thanks!

**Comment by BertrandBordage** [comment]
@ramiro: I optimized tests with django-cachalot enabled even more with version 1.0.3.
On my projects, the issue is solved now.

Could you test again, tell us the results, and reopen the issue if needed? Thanks!
