### ISSUE TITLE
500 response on cache miss

### ISSUE THREAD

**Issue by shakey-uk** [BertrandBordage/django-cachalot#14]
running django-cachalot with Django 1.8, memcached and ElastiCache

**Comment by BertrandBordage** [comment]
What is the traceback of the error? Otherwise I can’t help you.
Plus ElastiCache is not supported.

**Comment by BertrandBordage** [comment]
Same as #15, you’re using an unsupported cache backend with an unsupported Django version.

**Comment by rahulmuraliqllabscom** [comment]
I am using cachalot 1.2.1   with memcache  and   
the backend is
django.core.cache.backends.memcached.PyLibMCCache
recently I got a 500 on cache miss  (on memcache server time out)
the error log is

 File "/home/rahul/.virtualenvs/curbtab/lib/python3.4/site-packages/cachalot/monkey_patch.py", line 78, in inner
    cache_key, table_cache_keys)
  File "/home/rahul/.virtualenvs/curbtab/lib/python3.4/site-packages/cachalot/monkey_patch.py", line 37, in _get_result_or_execute_query
    data = cache.get_many(table_cache_keys + [cache_key])
  File "/home/rahul/.virtualenvs/curbtab/lib/python3.4/site-packages/django/core/cache/backends/memcached.py", line 101, in get_many
    ret = self._cache.get_multi(new_keys)
_pylibmc.ServerDown: error 47 from memcached_mget: (139802999972352) SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY, host: 52.77.36.107:11211 -> libmemcached/get.cc:314

is it a problem with cachalot or  the cache backend

**Comment by BertrandBordage** [comment]
Your memcached server is down, as written in the error message.

**Comment by rahulmuraliqllabscom** [comment]
But in that case it is suppose to go and fetch from the database right
In case of Cacheops it has a setting like 
CACHEOPS_DEGRADE_ON_FAILURE = True
which handles the situation

**Comment by BertrandBordage** [comment]
No it’s not, a part of your system is not supposed to fail randomly.

And in that case, it’s pylibmc that raises an exception, not django-cachalot, we’re not supposed to catch any possible exception to silence it, even with a boolean setting. That would make debugging a nightmare if multiple modules did that. And that would break multiple things: suppose someone wants to close the django server, if the `KeyboardException` error is catched by cachalot, the program will not be closed.

**Comment by rahulmuraliqllabscom** [comment]
Can you kindly suggest any workarounds

**Comment by BertrandBordage** [comment]
Start memcached?

**Comment by rahulmuraliqllabscom** [comment]
I am running memcached all the time this error came for just one single query but after that also the rest were working fine without me doing anything to start/restart memcahe

**Comment by BertrandBordage** [comment]
There’s either a problem with your connection or with your memcached configuration, probably the timeout you specify in Django `CACHES` is too small compared to what your infrastructure can provide? Anyway, you have to fix this issue, it will not only affect django-cachalot but also all other cache uses you do.

**Comment by rahulmuraliqllabscom** [comment]
Thank you for the insight I will try solving it from that angle
