### ISSUE TITLE
Thoughts on post cache invalidation signals?

### ISSUE THREAD

**Issue by harshil07** [BertrandBordage/django-cachalot#17]
Would love to be able to do some extra logic on invalidation of cache.
I was personally thinking it could be useful to invalidate api/response caches on query cache invalidations but would love to hear other use cases and see if this is a good thing to do in the first place.

**Comment by BertrandBordage** [comment]
I’m also considering this. I found it could be useful for a specific cache I am using in a client project.

Another useful feature could be an template tag to get the last invalidation timestamp for one or several models. That way, we could use it to do partial template caching. Something like:

```
{% load cachalot %}
{% get_last_invalidation auth.User yourapp.YourModel as last_invalidation %}
{% cache 86400 cacke_key last_invalidation %}
    […]
{% endcache %}
```
That way, this part of the template is updated when a change is done in the table `auth_user` or `yourapp_yourmodel`.

**Comment by harshil07** [comment]
Yep that sounds like a good feature as well.  I have previously done something similar by using a mix of django-reversion and the objects version to invalidate template fragments. But have since moved away from that plugin completely.

**Comment by BertrandBordage** [comment]
Fixed with 3798a1c.

**Comment by harshil07** [comment]
@BertrandBordage Thanks for turning around on that so fast. :+1:

**Comment by BertrandBordage** [comment]
You had a lucky timing: @helenwarren found an invalidation issue (#16) a few hours ago, plus python-memcached 1.54 introduced an error a few weeks ago. These 3 changes will be in django-cachalot 1.0.1, in a few minutes on PyPI ;)

**Comment by harshil07** [comment]
Great thanks.
