### ISSUE TITLE
Add documentation on time syncing

### ISSUE THREAD

**Issue by josephdrose** [BertrandBordage/django-cachalot#19]
Since the current time is used to determine validity of table cache keys, it's important that when deploying against multiple application servers, they all have time synchronized.  I'd like to suggest adding this to the docs somewhere prominently.

Even a few seconds difference was enough to cause issues for us in production.

**Comment by BertrandBordage** [comment]
Yeah, sure, that’s something to write in “Limits”, probably in a “Multiple servers” section.
Do you want to write it?

**Comment by josephdrose** [comment]
Multiple Servers

Django-cachalot uses the current server time to generate table cache keys.  These keys are later compared to cached results to determine if they are still valid.  In a multi-server deployment, it's important that all servers have a synchronized clock; if they do not, invalidations may not happen correctly.  A difference of even a few seconds can cause this to occur.

----

How's that sound?

**Comment by BertrandBordage** [comment]
Good :)
Do you want to make a pull request?
