### ISSUE TITLE
Potential bug when using django.contrib.gis

### ISSUE THREAD

**Issue by ebrelsford** [BertrandBordage/django-cachalot#21]
Apologies for the vagueness here, I've looked at this a bit and plan on coming back to it, but I thought I'd write this down in case you have any ideas.

[These lines](https://github.com/596acres/nycdata/blob/master/nycdata/nycha/views.py#L33-L36) in my Django site return inconsistent and incorrect results. They count the number of model instances within a geometry represented in another instance. I'm relatively sure the issue has to do with `django-cachalot` since [invalidating the model cache before each query](https://github.com/596acres/nycdata/blob/master/nycdata/nycha/views.py#L22-L28) fixes the problem.

Each time the sql is the same, and the parameters will be something like this:

    ('*', 41, True, True, 'private', True, 3, <django.contrib.gis.db.backends.postgis.adapter.PostGISAdapter object at 0x7fcd2a807790>, True)

My hunch right now is that the `PostGISAdapter` gets SHAed to the same value sometimes as it is reused even for different geometries, so the cache key is the same for multiple queries that use different geometries.

Please let me know if there's more info I can provide, and what you might suggest I look at next.

**Comment by BertrandBordage** [comment]
Indeed, that’s an invalidation issue, and I suppose you’re right about its cause.

Could you try with a custom cache key generator?
Define this function in a file:
```python
def get_query_cache_key(compiler):
    sql, params = compiler.as_sql()
    cache_key = '%s:%s:%s' % (compiler.using, sql, [(hash(p), type(p)) for p in params])
    return sha1(cache_key.encode('utf-8')).hexdigest()
```
And tell Cachalot to use it by setting `CACHALOT_QUERY_KEYGEN = 'path.to.your.get_query_cache_key'`

**Comment by ebrelsford** [comment]
Looks like that fixes it. Any chance of updating the key generator, or should I leave this custom one in?

Thanks for the help and the excellent library!

**Comment by BertrandBordage** [comment]
I’ll fix that in the next minor release, but I’m not sure if this is the fastest and cleanest solution to serialize all parameters.

**Comment by ebrelsford** [comment]
That makes sense, let me know if you'd like me to test potential fixes.

**Comment by BertrandBordage** [comment]
I just release 1.0.3 with a fix for this issue! I had trouble testing it, because I wanted to reproduce it without django.contrib.gis. And this is possible, only with BinaryField on PostgreSQL, as far as I know.

**Comment by ebrelsford** [comment]
I just tested it out and it appears to work from my side. Thanks for all your help!

**Comment by BertrandBordage** [comment]
You removed the custom cache key generator, right?

**Comment by ebrelsford** [comment]
Yep! :+1:

**Comment by BertrandBordage** [comment]
Ok :)
