### ISSUE TITLE
Unable to disable cache on a per-database basis.

### ISSUE THREAD

**Issue by danielsamuels** [BertrandBordage/django-cachalot#22]
I currently have a project with two database connections; a PostgreSQL database for all the usual Django things and an external MySQL data we're using to pull data from.  If objects get deleted from the external MySQL database using that provider's tools (not though Django) django-cachalot (obviously) doesn't know that's happened and continues to return data which no longer exists (and messes up some of the Django logic).  What would be great is if we could disable cachalot on the MySQL database, but keep it on the Django one - is this possible?

**Comment by BertrandBordage** [comment]
You can do this by customizing `CACHALOT_QUERY_KEYGEN` and raising an `UncachableQuery` exception if the query is using MySQL.

Suppose the aliases you use are `'default'` for PostgreSQL and `'mysql'` for MySQL, you can write this:
```python
from cachalot.utils import UncachableQuery, get_query_cache_key as original_query_keygen

def get_query_cache_key(compiler):
    if compiler.using == 'mysql':
        raise UncachableQuery
    return original_query_keygen(compiler)
```
Then define `CACHALOT_QUERY_KEYGEN = 'path.to.where.you.put.get_query_cache_key'` in your settings.py.

It should be that easy. Could you confirm?

**Comment by danielsamuels** [comment]
That worked well, thank you. I do still think it would be nice to have an option, perhaps in the `DATABASES` setting which gives you this control without adding utils. It's a nice workaround though. Thanks again.

**Comment by BertrandBordage** [comment]
I prefer providing simple workarounds for edge cases like this instead of adding a ton of settings. Adding settings has a performance cost since they are dynamic in cachalot.
With a flexible function setting like this, a lot of edge cases can be handled without having to wait for the next release to change its behaviour :)
