### ISSUE TITLE
Ability to set a prefix

### ISSUE THREAD

**Issue by karthikbgl** [BertrandBordage/django-cachalot#23]
This is not an issue - but an enhancement request. 

Was wondering if there could a setting which allows to set a cache key prefix? It would help in debugging, etc..  (well to a certain extent at least)

**Comment by BertrandBordage** [comment]
You can add a cache key prefix globally to Django using [`KEY_PREFIX`](https://docs.djangoproject.com/en/1.7/ref/settings/#key-prefix) in your `CACHES` setting.

If you want to add a cache key prefix only to django-cachalot, define a custom define the setting `CACHALOT_QUERY_KEYGEN` to point to a function like that:
```python
from cachalot.utils import get_query_cache_key as original_query_keygen

def get_query_cache_key(compiler):
    return 'your_prefix:' + original_query_keygen(compiler)
```
