### ISSUE TITLE
Add a whitelist

### ISSUE THREAD

**Issue by orf** [BertrandBordage/django-cachalot#29]
There is a blacklist of tables that shouldn't be cached, can we get a whitelist as well?

**Comment by BertrandBordage** [comment]
It’s not possible at the moment, even by using `CACHALOT_QUERY_KEYGEN` or `CACHALOT_TABLE_KEYGEN`.

But the question is: do we need it?
Why do you exactly need to whitelist some tables? Maybe there’s a better solution.  If not, I’ll consider adding it (after #27, which is the priority at the moment).

**Comment by orf** [comment]
We maintain a pretty large (and very critical) Django app and we are very interested in using this library for some easy speedups. Unfortunately the only way we are ever going to be able to add this library is to do it model by model, ensuring all existing functionality is retained, which requires a whitelist (or we could just blacklist all the tables and remove one at a time, but that's a bit icky).

In any case we only have a few models that would really benefit from this, so it would be better for us to explicitly cache those and only those.

**Comment by BertrandBordage** [comment]
OK, that’s a valid use case for me, I’ll add a setting in django-cachalot 1.1.

**Comment by BertrandBordage** [comment]
Fixed by a8b77c6e3264668e0b9cec714c9c23712ad738b5. It’ll be available shortly in release 1.1.
