### ISSUE TITLE
django.db.models.loading.get_models will be removed in Django 1.9

### ISSUE THREAD

**Issue by jjmontalbo** [BertrandBordage/django-cachalot#33]
`django.db.models.loading.get_models` will be removed in Django 1.9. In my Django 1.8.6 installation, the following warning is thrown:

    /home/xxx/.virtualenvs/xxx/local/lib/python2.7/site-packages/cachalot/panels.py:10: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
      from django.db.models.loading import get_models

`django.apps.apps.get_models` is the equivalent function in Django 1.7+.

    >> from django.db.models import loading
    >> from django.apps import apps
    >> apps.get_models() == loading.get_models()
    True

**Comment by JockeTF** [comment]
Solved by #35.

**Comment by BertrandBordage** [comment]
Indeed, I correctly replaced it everywhere except in the django-debug-toolbar panel. Thanks for this reporting!
Fixed by fcc77fa18e5fd2c3461fcd6eb35f816c737ef684.
