### ISSUE TITLE
How to monitor requests?

### ISSUE THREAD

**Issue by softshape** [BertrandBordage/django-cachalot#34]
Is there any way to monitor how much requests django-cachalot reads from cache and how much passes to DB backend? I've just setup django-cachalot and can't really feel the difference, so I want to be sure it really works as supposed.

**Comment by BertrandBordage** [comment]
You can use django-debug-toolbar with the `CachalotPanel` installed. Then you can:

1. See how much SQL requests are executed with django-cachalot, the first time you arrive on a page and the following times
2. Disable django-cachalot by unticking the django-cachalot panel and reloading the page
3. Compare with the number of SQL requests executed

It’s quite manual and could be more explicit in the debug toolbar, but it requires some work I’m not currently willing to do. If someone wants to do it, feel free to send a pull request!
