### ISSUE TITLE
Unable to run the tests without pytz

### ISSUE THREAD

**Issue by xino12** [BertrandBordage/django-cachalot#39]
I don't know if you are aware and it's something done on purpose but if you clone the repository and try to run the tests you get a misleading error that says that cachalot has not module tests.

That's because when importint cachalot.tests there an error that the pytz packet is missing. It would be nice to have it in the file runtests_requirements_py2.txt.

Thanks

**Comment by BertrandBordage** [comment]
That’s right, I’ll add it.

**Comment by BertrandBordage** [comment]
Fixed by e2d14997e0590bd578ccf5e3b9f9e35796b0570f.
