### ISSUE TITLE
Cache invalidation problems with asynchronous tasks

### ISSUE THREAD

**Issue by rahulmuraliqllabscom** [BertrandBordage/django-cachalot#46]
I am using celery with django for some asynchronous tasks but now I find that  when table row is updates by a  celery worker process  cachalot is not invalidating the cache

**Comment by orf** [comment]
Dat title

**Comment by BertrandBordage** [comment]
Strange, there should be no problem, I specifically designed django-cachalot with asynchronous tasks in mind. I use cachalot along with [RQ](https://github.com/nvie/rq) on several projects without a single issue.

Are you sure you’re using the same cache storage on the server and celery? If so, did you read [the limits of Locmem](http://django-cachalot.readthedocs.org/en/latest/limits.html#locmem)?

By the way, I suggest you try another solution than celery. **I lost a full-time week** in 2014 trying to figure out why it was working only partially on my projects (often lost tasks for no reason using only Redis). I still don’t get it, but switching to RQ was an instant-working revelation. Besides this unreliability, I find celery heavy, slow, and poorly coded (try to write tests for an asynchronous celery task **without** `CELERY_ALWAYS_EAGER` and welcome to a world of pain).

**Comment by rahulmuraliqllabscom** [comment]
Sir, 
Firstly sorry for the late reply I was out of town for the weekend. I am thankful that you noticed my issue, I am a newbie to the techworld this is my first full scale project. Ours is a small firm and I am the only one working on Django. I don't have anyone around for help, when it came to the requirement that I needed some task to be done asynchronously first solution I found was to use celery, so I went ahead with it and things were working fine for me till it came down to this issue. I read High performance Django by the team from Lincolon Loop In that they suggest using jhonycache for queryset cache, but because of my blunder and little knowledge I had already seleced Django1.8 and python3 both of which are not compatible with johnycache, there they have mentioned that johnycache also has the same issue and could be overcomed by  adding 

import johnny.cache
johnny.cache.enable()

into the projects __init__.py  file

Other than this issue Cachalot was working fine I reviewed database logs and only new quires were directed to database others were served from cache. I also had some issues in saving of a model a filed was simply going null eventhough I saved values to it. In the above comment you have asked 
 
Are you sure you’re using the same cache storage on the server and celery?

I have not set any separate cache for celery. I use memcached for cache storage and have set it as default cache in django settings file. I am using the package django-celery. 
When I did load testing with a heavy dataset I found that I badly need queryset caching for some queries 

Please help me sir I am stuck on this 
Also can you suggest me some good advanced django tutorials.

**Comment by JockeTF** [comment]
We have also been seeing some invalidation issues recently, which @devoto13 suggested may have something to do with [PYTHONHASHSEED](https://docs.python.org/3.4/using/cmdline.html#envvar-PYTHONHASHSEED).

We had `PYTHONHASHSEED` set to `random`as recommended by [Django's Deployment Checklist](https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/#python-options). This could lead to issues since Cachalot [now uses the built-in hash function](beac70251f509a48d80e2c03add98b42974f74d4) instead of SHA-1. Django and Celery would get different hash seed values, so their cache keys may no longer match.

I'm currently testing out static `PYTHONHASHSEED` values in our development environment to see if this solves the issue.

**Comment by rahulmuraliqllabscom** [comment]
thank you for the concern you are showing

**Comment by BertrandBordage** [comment]
@JockeTF You’re right. I didn’t face the issue as I always have this environment variable set to `1`. I made a mistake, I’ll fix it a bugfix release I’ll issue in the following days. Many thanks for identifying this cause!

**Comment by BertrandBordage** [comment]
@rahulmuraliqllabscom: Are you using Python 3.3, 3.4 or 3.5? If so, please update to the new django-cachalot 1.2.1 and this issue can be closed.

**Comment by rahulmuraliqllabscom** [comment]
Thank you all for the help, now things are working fine also I was able to come across the python3 random hashseed property.
