### ISSUE TITLE
Cache Invalidation Problem in DRF

### ISSUE THREAD

**Issue by lishenzhi** [BertrandBordage/django-cachalot#47]
I am using cachalot with Django Rest Framework and redis. One viewset has a complicated queryset, with slecte_related and prefetch_related. post in this viewset did not invalidate the existing cached queries. I am using redis master/slave setup. Is this the problem?

**Comment by BertrandBordage** [comment]
It’s already documented: http://django-cachalot.readthedocs.org/en/latest/limits.html#replication-server
Is this fixing the issue?

**Comment by lishenzhi** [comment]
Hi, Bertrand,

Thanks for the reply. Unfortunately, the problem is not related to replica. I tried it with one node only, and the invalidation still does not work.

I am using DRF with Postgres and Redis (one master only). The query is pretty complicated. It has lots of joins using select_related and followed by several prefetch_related.

I tried to add the receiver for signal like you suggested, but that was not triggered. Please bear with my dumb questions:


  1.  which function will be used to invalidate the queryset in DRF? The _patch_write_compiler or patch_cursor_execute?
  2.  For _patch_write_compiler(original), I will need to add a receiver for the post_invalidation signal, right? I tried to add that into my code, and I got error 'maximum recursion depth exceeded while calling a Python object'. Do you have any clue about it?
  3.  I tried to check whether I could use _patch_cursor_execute(original), but seems django postgres backend does not have CursorWrapper.execute in base.py, can that still work?

Thanks a lot for your time and help!
Shenzhi

**Comment by BertrandBordage** [comment]
I’m not sure I fully understand your questions, but I’ll try to answer them:

1. You must not use or redefine `_patch_write_compiler` or `_patch_cursor_execute`. Querysets are invalidated in the `execute` method of SQL write compilers (thanks to `_patch_write_compiler`). They are also invalidated during a `cursor.execute` call (thanks to `_patch_cursor_execute`) only if `cursor.execute` is triggered directly by your code, not by a SQL compiler.
2. What do you mean by “For _patch_write_compiler(original)”? The receiver for `post_invalidation` must be in file loaded during the project initialization, typically in models.py. About the infinite recursion, I can’t tell without seeing your code.
3. As stated in 1, you must not use `_patch_cursor_execute`. In Python, a variable/function starting with an underscore means that it shouldn’t be used, unless you know exactly what you’re doing.

**Comment by BertrandBordage** [comment]
Closing it as I don’t really understand the problem, if it exists. Re-open if relevant.
