### ISSUE TITLE
monkey_patch did not read current settings

### ISSUE THREAD

**Issue by arunaharsa** [BertrandBordage/django-cachalot#49]
Hi, can you help me with the following:
- lets say I run migrate
- django_cachalot monkey_patch will run, to invalidate cache
- however i received `redis.exceptions.ConnectionError: Error 111 connecting to None:6379. Connection refused` --> it happened because django-cachalot still looking for redis at :6379, while my application used redis through different endpoint, lets say SOME_OTHER_REDIS_URL (stated in my app settings.py)

Have been running over the place, but can't find out why the application setting did not apply (it used default settings). This behavior does not exist in normal caching operation, only when I run from management console, eg. manage.py migrate or manage.py invalidate_cachalot

**Comment by BertrandBordage** [comment]
Mmm… I’m not sure I understand. What is `SOME_OTHER_REDIS_URL`? Could you send a minimal example for me to reproduce the settings issue?

**Comment by BertrandBordage** [comment]
Closing this issue until more info is provided.
