### ISSUE TITLE
Docs benchmarks should state which versions were used

### ISSUE THREAD

**Issue by artscoop** [BertrandBordage/django-cachalot#5]
Hi,
I've had a look at the benchmarks but this is unclear which versions of SQLite, MySQL and PostgreSQL were used. Postgres seems slow compared to the others, thus I kept wondering "is this 8.4 ?"

**Comment by BertrandBordage** [comment]
Fixed by 13f296f19053ab3bf75685f65cb96ff8e6ca3c7b.
