### ISSUE TITLE
Returning stale data after object reload

### ISSUE THREAD

**Issue by rantecki** [BertrandBordage/django-cachalot#53]
I seem to be running into a few cases where I'm getting stale data returned.  One is as follows:

Using Plata (an e-commerce module for Django), there's an OrderPayment model with an FK to the Order model.  There comes a time during payment processing when the following occurs:
```
payment.save()
order = order.reload()
```
order.reload() reloads the object from the database using the existing id.

There seems to be quite frequent cases where the reloaded order does not acknowledge the newly created payment, and so thinks the order is not yet paid.  Disabling caching for these two tables seems to be solve the issue.

Is there a known issue with invalidation in this kind of situation?

**Comment by BertrandBordage** [comment]
No need to fetch the object again: the foreign key is contained in `OrderPayment`, so you don’t need to reload any `Order` object to list all payments for an order.
Using the reverse relation normally always work with django-cachalot, and there doesn’t seem to be any caching stuff interfering in plata.

So there can be three causes:
- you’re facing the [multiple servers clock synchronisation issue](http://django-cachalot.readthedocs.io/en/latest/limits.html#multiple-servers-clock-synchronisation)
- you’re facing the [replication server issue](http://django-cachalot.readthedocs.io/en/latest/limits.html#replication-server)
- you found an invalidation issue in django-cachalot (congrats!)

**Comment by rantecki** [comment]
Thanks for the response.  I am actually running on multiple servers, and it appears one didn't have the timezone set correctly.  I will investigate to see if this actually resolves the issue.

**Comment by BertrandBordage** [comment]
I close this since we don’t have more info. Reopen if you have details about it.
