### ISSUE TITLE
Cut a new version for postgres compatibility

### ISSUE THREAD

**Issue by schuyler1d** [BertrandBordage/django-cachalot#58]
I don't suppose you could cut a new version with this fix:
https://github.com/BertrandBordage/django-cachalot/commit/b9f84f8047414a280490518641bca25be10d258b

We're not able to use django 1.9.4 which prefers postgres without this.

Awesome library!  The drop-in nature of it, has literally saved many projects!

**Comment by BertrandBordage** [comment]
That’s planned, I will finish the new version in a few days.

**Comment by BertrandBordage** [comment]
Closing if favor of #60.
