### ISSUE TITLE
support for Django 1.10?

### ISSUE THREAD

**Issue by genxstylez** [BertrandBordage/django-cachalot#60]
as titled

**Comment by BertrandBordage** [comment]
Already discussed in #59 & #52, already in master, coming in a few days on PyPI.

**Comment by genxstylez** [comment]
@BertrandBordage Thanks for the update.

**Comment by BertrandBordage** [comment]
1.2.0 shouldn’t be used, it’s an unsafe version. But 1.2.1 works with Django 1.10, there are just a few warnings and other trivial issues like this.

**Comment by BertrandBordage** [comment]
1.3.0 is released, with Django 1.10 support!
