### ISSUE TITLE
Cachalot is making too many calls to memcache server

### ISSUE THREAD

**Issue by debanshuk** [BertrandBordage/django-cachalot#63]
We are using Cachalot in one of our projects and and we are observer too many get_multi calls to our memcache servers on all our environments. On my local environment when I run the same code with cachalot disabled number of hit to memcache reduces significantly. With Cachalot enabled the number of get_multi calls is in 100s even for opening a list page in Django admin.

Most of the call retrieve keys which have some floating point values saved for them and these floating point values looks like to be epoch timestamps. Following are few example keys and their values retrieved from get_multi calls:
```
get_many ['f330760c95588f8c795d0df3f699f90ae143e26a', 'b5ac959681ff06eff632d25a5961a4d3cad09b42', '8c6f559b37d1caa6e3d892aa317eca64377a43af', '887f8247d0ff979264c73b069f790024b2aa98e1', '5c01fcd741777a41b0557cb7a62501de3a0b31d6'] {'5c01fcd741777a41b0557cb7a62501de3a0b31d6': (1476366950.845727, []), '8c6f559b37d1caa6e3d892aa317eca64377a43af': 1476366950.486771, 'f330760c95588f8c795d0df3f699f90ae143e26a': 1476340903.45008, '887f8247d0ff979264c73b069f790024b2aa98e1': 1476340903.45008, 'b5ac959681ff06eff632d25a5961a4d3cad09b42': 1476340903.45008}
```

And following is a set_multi call which sets one such key:
```
set_many {'8c6f559b37d1caa6e3d892aa317eca64377a43af': 1476366950.903075}
```

Could someone please tell me why Cachalot is caching these floating point numbers and why there are so many cache hits of these keys?

**Comment by BertrandBordage** [comment]
This is the table invalidation system, this is perfectly normal. It is based on timestamps, as you correctly assumed. And of course, django-cachalot uses the cache, so the number of cache hits is greater using it.

What do you mean by “too many get_multi calls”? Is this causing a problem?

**Comment by debanshuk** [comment]
By too many I mean in some API calls we are seeing more that 2000 average cache hits (one API also have more that 6000 avg cache hits). Which are significantly more than the number of DB queries those APIs are doing.

**Comment by BertrandBordage** [comment]
How many DB queries are executed normally by the page generating 6000 cache hits?

**Comment by BertrandBordage** [comment]
Closing this issue for the moment as it seems invalid. Reopen if you have more information!

**Comment by debanshuk** [comment]
Sorry for very late reply. In case of 8000 cache hits there were more than 6000 DB queries which were executed (though I don't remember the exact number). After reducing the DB queries from thousands to hundreds the cache hits also got reduced to hundreds. 

@BertrandBordage, My reason for opening the ticket was the difference between number of DB queries and the number cache hit (around 1000, in this case). But it's apparent from your following comment that it's normal.

> This is the table invalidation system, this is perfectly normal. It is based on timestamps, as you correctly assumed. And of course, django-cachalot uses the cache, so the number of cache hits is greater using it.

With number of queries in hundreds, number of cache hits are also in hundreds (though greater than the number of queries, they are taking very small amount of time). 

Thanks for the replies and patience :).
