### ISSUE TITLE
CACHALOT_ENABLED=False doesn't seem to disable all aspects of the cache

### ISSUE THREAD

**Issue by rantecki** [BertrandBordage/django-cachalot#64]
I have a project using celery.  For local development I use `LocMemCache` and also disable cachalot via `CACHALOT_ENABLED = False`, as the docs say it won't work well in this scenario (plus I don't generally want it for development anyway).

The problem is, even with cachalot disabled I keep running into issues with stale data for models written to from celery tasks and read by the main process.  If I add the table to `CACHALOT_UNCACHABLE_TABLES` the issue disappears.

So it would seem that CACHALOT_ENABLED doesn't control all cache-related functions.

**Comment by BertrandBordage** [comment]
[As stated in the docs](http://django-cachalot.readthedocs.io/en/latest/limits.html#locmem), just don’t use LocMem with django-cachalot in a multiple processes project.
That being said, this should work with `CACHALOT_ENABLED = False`. Maybe you have something else going on, for example maybe `CACHALOT_ENABLED` is only `False` in the web server, but not in the Celery task?

**Comment by rantecki** [comment]
I've verified that `CACHALOT_ENABLED` is evaluating to `False` in both the web server and celery task.

I'm using LocMem on my dev machine only, in production it's using Memcached.  I wish to disable cachalot for the dev environment only.

I guess I'll have to resort to customising the `INSTALLED_APPS` via local settings.

**Comment by stunaz** [comment]
I have the same issue too, using `redis`, I cant disable django cachalot using the settings 'CACHALOT_ENABLED = FALSE'

**Comment by BertrandBordage** [comment]
I close this as I can’t create a miracle turning `LocMemCache` into a cache shared between processes.
I also mark this as requiring more info, as it’s not clear whether @rantecki faces this issue in development or in production. @stunaz’s case also needs more info.

**Comment by pfcodes** [comment]
This is still an issue in 2024
