### ISSUE TITLE
CachalotPanel shows nothing

### ISSUE THREAD

**Issue by tylerecouture** [BertrandBordage/django-cachalot#73]
I'm not having some difficulty determining if Cachelot is working for me, and the CachelotPanel for debug-toolbar isn't helping, as it's blank.

Using Django 1.9.7 and SQLite test db (I'm pretty much new to everything django)

I have:
```
INSTALLED_APPS += ('cachalot',)
DEBUG_TOOLBAR_PANELS += ['cachalot.panels.CachalotPanel', ]
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': 'unix:/tmp/memcached.sock',
    }
}
```
My debug-toolbar's CACHE panel shows some big long entries:
(dict_keys(['33cd0b10f8c2fd53802b0948820b8b58da6bb27c', .... ']),)

But the CACHELOT panel is blank:
```
Database 'default'
Application 	Model 	Last invalidation
```

Any ideas what I might be doing wrong?

And there is no noticeable speed difference on a page that currently takes about 10 seconds to load (334 queries) =P

**Comment by BertrandBordage** [comment]
Did you check that memcached is running?

**Comment by BertrandBordage** [comment]
Closing this for now, will be reopened if it turns out to be something else than memcached not running.

**Comment by katsika** [comment]
@BertrandBordage I have the same problem with Cachalot. Debug panel shows nothing except CACHALOT title.

Versions used:
```
Django 2.1.3
Python 3.7.4
Cachalot 2.1.0
django-redis  4.10.0
```

Redis is my cache backend. I believe caching itself works as I can see dramatic drop in rendering times when `cachalot` is added to `INSTALLED_APPS`.

I have added cachalot panel by setting:
```
DEBUG_TOOLBAR_PANELS = [
    "debug_toolbar.panels.versions.VersionsPanel",
    "debug_toolbar.panels.timer.TimerPanel",
    "debug_toolbar.panels.settings.SettingsPanel",
    "debug_toolbar.panels.headers.HeadersPanel",
    "debug_toolbar.panels.request.RequestPanel",
    "debug_toolbar.panels.sql.SQLPanel",
    "debug_toolbar.panels.staticfiles.StaticFilesPanel",
    "debug_toolbar.panels.templates.TemplatesPanel",
    "debug_toolbar.panels.cache.CachePanel",
    "cachalot.panels.CachalotPanel",
    "debug_toolbar.panels.signals.SignalsPanel",
    "debug_toolbar.panels.logging.LoggingPanel",
    "debug_toolbar.panels.redirects.RedirectsPanel",
]
```

Unfortunately `DEBUG_TOOLBAR_PANELS += ['cachalot.panels.CachalotPanel', ]` gives me
```
    DEBUG_TOOLBAR_PANELS += ['cachalot.panels.CachalotPanel', ]
NameError: name 'DEBUG_TOOLBAR_PANELS' is not defined
```
error.

Redis is definitely running, when I turn it off I get error saying it can't connect to it.

Thanks.
