### ISSUE TITLE
Ignore incompatible backends

### ISSUE THREAD

**Issue by OmegaDroid** [BertrandBordage/django-cachalot#74]
Hi,

Earlier I ran into an issue with one of the databases in my system being incompatible with django-cachalot, however it would be nice to have caching across my other dbs.

It would be useful in this case if we would ignore incompatible databases, excluding them from caching, maybe giving a warning rather than an error from the integrity check or maybe having a setting to exclude database aliases.

Do you see any reason why this wouldn't work?

Cheers

**Comment by flash286** [comment]
I have same issue, we using a custom database backend for working with salesforce, and I want just don't use cachalot for this backend. Is there way to do this?

**Comment by agronick** [comment]
I have the same issue. I need to extend my backend to add timestamps for modules that don't set theirs. This should be a warning, not an error.

**Comment by suoinguon** [comment]
I have following incompatible but it seems still running well. 


?: (cachalot.E001) `django_bmemcached.memcached.BMemcached` is not compatible with django-cachalot.
?: (cachalot.E001) `django_postgrespool` is not compatible with django-cachalot.

What about SQL Server support?

**Comment by danielsamuels** [comment]
I've just run into this after adding SQL server as an available database:

``` `sqlserver_ado` is not compatible with django-cachalot.```

Would be great to be able disable cachealot on a per-database level.

**Comment by izimobil** [comment]
I have the same issue with [django-tenant-schemas](https://github.com/bernardopires/django-tenant-schemas) and ended up adding `SILENCED_SYSTEM_CHECKS = ['cachalot.E001']` to my settings file.

I agree it would be great to add the possibility to override (or to extend) the `VALID_DATABASE_ENGINES` and `VALID_CACHE_BACKENDS` variables used in cachalot/apps.py.

**Comment by Surgo** [comment]
I'm also need mechanism to skip these validations.

**Comment by BertrandBordage** [comment]
Hi everyone, thanks for all the input regarding the compatibility checks.

It took me some time to process all this to figure out what solution to choose. I wanted to do something simple to use, but while keeping it as clear as it was until now.

So I ended up with an implementation in this commit: https://github.com/BertrandBordage/django-cachalot/commit/da4e21b5156759fa117f516c9dfd919061b71220.

There is now a new `CACHALOT_DATABASES` setting, allowing users to define on which databases django-cachalot is enabled.

By default it is set to `'supported_only'`, meaning that django-cachalot is only enabled on supported databases (thanks @OmegaDroid for the suggestion!). So by default you won’t get warnings or errors (you may only get a warning if all your databases are unsupported, meaning that django-cachalot will be useless).

But you can also manually specify databases, by setting for example `CACHALOT_DATABASES = ['default', 'replica']`.
If you specify an unsupported database, you get a warning.

I hope this new setting & behaviour will be clear enough and cover most cases :)

**Comment by Surgo** [comment]
@BertrandBordage Wow! Thank you 😊

**Comment by OmegaDroid** [comment]
This looks great, thanks @BertrandBordage
