### ISSUE TITLE
How to use cachalot with only postgresql db?

### ISSUE THREAD

**Issue by Bilyalov** [BertrandBordage/django-cachalot#79]
I have 2 databases: postgresql and cassandra db. I want to use cachalot with postgresql, and ignore the cassandra db. How to do it?

**Comment by BertrandBordage** [comment]
See this answer: https://github.com/BertrandBordage/django-cachalot/issues/22#issuecomment-120070246.

**Comment by BertrandBordage** [comment]
You can now use `CACHALOT_DATABASES` as well, introduced in django-cachalot 1.5.0.
