### ISSUE TITLE
Caching large querysets

### ISSUE THREAD

**Issue by farridav** [BertrandBordage/django-cachalot#85]
I'm using your library in an appengine project (Thanks for your contribution :)), and the memcache server has a fixed item limit of 1MB, when the queryset that cachalot returns is > 1MB, then it fails spectacularly, 

This is not really the fault or responsibility of cachalot, but it got me thinking, wouldn't it be a small effort/big win to use `zlib` or `gzip` compression on the querysets before caching them? This wouldn't necessarily solve my problem, as a compressed queryset may still exceed 1MB, but it would improve efficiency all round.

to solve my problem I'm guessing ill need to find a way to get my caching backend (memcache) to chunk large items before storing them, and when retrieving them. Happy to hear If you know of an existing solution to this, otherwise ill roll my own.

Happy to hear thought/suggestions or if I've missed the mark somewhere.

**Comment by BertrandBordage** [comment]
Compressing query results is out of the question, as it decreases performance drastically. I made a test, with a 1MB result, compressing + decompressing with zlib takes 10 ms. Besides, as you mentioned, it doesn’t solve the problem.

The options you have are in my opinion:
- Use a different cache backend, for example LocMem if you have only one worker, or FileBased if you have multiple workers. These caches are extremely simple and usually snubbed by developers, but I never understood why. Both are reliable, have excellent performance (thanks to the filesystem cache in FileBased’s case), and don’t require any dependency. I guess devs love to use trendy software like Redis or elasticsearch, even when that’s useless & wasteful.
- Deploy your code somewhere else.
- Stop using django-cachalot.

**Comment by artscoop** [comment]
(I think the problem of the LocMem cache is that it's not shared between Django workers and most developers think multi-worker-wise. For the File one however, I'd say they tend to forget that the system file cache can speed up things a bit)

**Comment by farridav** [comment]
Thanks for your input, I'm going to keep using cachalot because it's providing a great performance boost to my site, moving away from appengine is not an option for me right now, I have a read-only file system, multiple workers/autoscaled servers and can't warrant the use of an external cache (outside of appengine)

What I've ended up doing was identifying the tables that yield such a massive queryset, and doing some more ORM optimisation (mainly it's the contents of JSONfields), though in any other project, I would probably not do in appengine again, and allow myself the freedom of using a different cache, or adjusting item size limit.

Thanks again for your input, and your contribution

**Comment by tolsac** [comment]
Can you split the cache data and store it into multiple keys ?

mykey.1
mykey.2
...
