### ISSUE TITLE
Assignment_tag is not compatible with Django 2.0

### ISSUE THREAD

**Issue by pm13** [BertrandBordage/django-cachalot#97]
Django 2.0 removed support for assignment_tag, simple_tag could be used as replacement from Django 1.9:
https://docs.djangoproject.com/en/2.0/releases/1.9/#assignment-tag

Django-cachalot use assignment_tag:
https://github.com/BertrandBordage/django-cachalot/blob/a279e38dfd6e6da317427901279ff2597c7e86fc/cachalot/templatetags/cachalot.py#L9

**Comment by tawanda** [comment]
I have made a pull request

https://github.com/BertrandBordage/django-cachalot/pull/105

**Comment by BertrandBordage** [comment]
Fixed by 74e000b8e2b7f4cf9f31319a83d21620ea7b747d.
