### ISSUE TITLE
Invalidation doesn't succeed on save.

### ISSUE THREAD

**Issue by svemaraju** [BertrandBordage/django-cachalot#99]
The settings.py has the basic configuration set, i.e. just 'cachalot' included in installed_apps.

```
>>> from cachalot.api import get_last_invalidation
>>> import datetime
>>> last_user = User.objects.last()

>>> last_user.created_at
datetime.datetime(2018, 1, 19, 12, 54, 43, 685800, tzinfo=<UTC>)
# 12:54:43
>>> datetime.datetime.fromtimestamp(get_last_invalidation(User))
datetime.datetime(2018, 1, 19, 12, 35, 31, 785219)
# 12:35:31
```

The query `User.objects.last()` contains the latest record, but the result `get_last_invalidation` seems to show as if the cache is outdated. I am little confused by this.
I suspect there is something wrong going on here. I welcome any suggestions.

**Comment by BertrandBordage** [comment]
Could you show us the User model you’re using? Because `User.created_at` does not exist in Django’s `User` model.

Apart from that, maybe you have multiple servers for your project? See http://django-cachalot.readthedocs.io/en/latest/limits.html#multiple-servers-clock-synchronisation

**Comment by BertrandBordage** [comment]
Closing for now, please give more info.
